### ISSUE TITLE
create PR grooming plugin

### ISSUE THREAD

**Issue by monkeypants** [bugflow/gh-ticket-gnome#14]
``` gherkin
As a project tech lead
I need a PR grooming plugin
so that I can ensure my desired process is followed
```

I imagine `.gnome.yml` might look something like:

``` yaml
plugins:
 - PRChecklist:
   - code_review: Code has been reviewed
   - test_coverage: New/Changed code has good test coverage
   - builds_ok: This code builds OK in my local environment
```

And as a result:

``` gherkin
Given I have a repo gnome
And I have PRChecklist plugin enabled
And at least one checklist item is defined
When someone makes a PR
Then the gnome makes a PR Checklist comment on the PR
```

PR CHecklist comment might look something like this:

-----------------
PR Checklist:
 * [ ] Code has been reviewed
 * [ ] New/Changed code has good test coverage
 * [ ] This code builds OK in my local environment
-----------------

Also, another result of the plugin:

``` gherkin
Given I have a repo gnome
And I have PRChecklist plugin enabled
And at least one checklist item is defined
When someone merges a PR
And the checklist is not all checked
Then the gnome raises a ticket to query the merge
And the raised ticket is assigned to the person who merged the PR
```

The raised ticket might like something like this

-----------------
When PR #1234567 was merged, the following *PR Checklist* items were not checked:
 * This code builds OK in my local environment

Was this an accident? Please re-check and close this ticket after making any necessary rectification.

If this checklist item was deliberately omitted, please explain why it wasn't appropriate for this PR (then close the ticket).

-----------------

**Comment by monkeypants** [comment]
hey @ltankey, I raised this ticket in response to our conversation this morning. Did I miss anything, is does that just about capture the requirement?

**Comment by ltankey** [comment]
I think that captures it!

I'm not sure about the additional ticket - it might be annoying, but then it shouldn't be happening every time.  Perhaps there's an override option, or perhaps we just keep it simple and accept that the user will have to close the raised ticket.

**Comment by monkeypants** [comment]
```
plugins:
 - PRChecklist:
   - items:
     - code_review: Code has been reviewed
     - test_coverage: New/Changed code has good test coverage
     - builds_ok: This code builds OK in my local environment
  - raise_issues: True
```
???

**Comment by ltankey** [comment]
Yes or even potentially a `comment_on_original_ticket`, with something like

```
A pull request was closed for this issue, but it doesn't look like code review checklist was completed.
```

It then provides the QA stream with more information

**Comment by monkeypants** [comment]
if PR with no ticket reference, ask for one?

**Comment by ltankey** [comment]
Yeah in this context, they shouldn't be doing a PR without a  ticket, so that would be a check something should do. Might be a task for this plugin, particularly if it is responding to an opened PR

**Comment by monkeypants** [comment]
what about commits without ticket reference?

**Comment by ltankey** [comment]
I think that's a style thing. I've never minded commits that don't have references if they're part of a PR that does, as it chews up precious message space. We could have a nag option but it feels like more of a chatops feature

**Comment by monkeypants** [comment]
precious message space on git commit comments? they can be as big as you like (practically).

first line -50 characters is good practie
blank line
as much stuff as you can be bothered writing...

**Comment by monkeypants** [comment]
but nvm; the question is "should PR Checklist plugin have an opinion about linking tickets to PRs?" Maybe that should be a different policy.

**Comment by ltankey** [comment]
I've never liked those other lines, but I take the point.

In any case, whilst it isn't something I'd use it doesn't mean someone else wouldn't

**Comment by monkeypants** [comment]
let's build it if/when we need it :)

**Comment by ltankey** [comment]
Yeah you're probably right. It could be a "ensure referential integrity of PRs" policy

**Comment by monkeypants** [comment]
Maybe we should rename "plugins" to "opinions".

**Comment by monkeypants** [comment]
And make naming convention that says what the opinion is.

 * PRChecklistShouldBeChecked
 * PRShouldReferenceIssue

**Comment by ltankey** [comment]
Sounds like a good way of having things named by what they do, which is good

**Comment by ltankey** [comment]
Very declarative :)

**Comment by monkeypants** [comment]
.gnome.yml
``` yaml
opinions:
 - PR_checklist_should_be_checked:
   - items:
      - code_review: Code has been reviewed
      - test_coverage: New/Changed code has good test coverage
      - builds_ok: This code builds OK in my local environment
  - raise_sooky_tickets: True
 - PR_should_reference_issue
 - verbose_logging_is_good
 - use_a_sorting_hat
```
