### ISSUE TITLE
opinion: UseRoleLabels

### ISSUE THREAD

**Issue by monkeypants** [bugflow/gh-ticket-gnome#16]
This practice is where we have traditionally made a set of light blue TODO labels, that corespond to internal roles within the team. For example:

 * TODO: code change
 * TODO: manual QA
 * TODO: QA automation

The purpose of these tags is to facilitate communication within the team about who should do what next. It's kind of like re-assigning tickets to each other, except in a team where each "role" can be done by more than one person (e.g. manual QA 2 testers), the developer doesn't really care which one does the tests, so assigning it to someone in particular doesn't make sense. Instead, the dev who fixed the bug might say "I think I fixed it, please check".

This auto-gnome opinion would:
 * ensure the light-blue tags existed (roles specificed in the .gnome.yml)
 * optionally, if "require_ACK: True", then the gnome could sook in #general if role labels added without an subsequent comment.

Maybe we could even have the idea of "role_members" or "role_managers". If a role label was added, then withing X hours if no role members ACK it with a comment (i.e. make a comment after the role was applied, any comment will do), then the role_manager get's pinged by the gnome.

This would be helpful to keep things moving. The purpose of this opinion is to encourage people to continuously groom appropriately for their role.

**Comment by monkeypants** [comment]
```yaml
opinions:
 - UseRoleLabels:
   - roles:
     - code_change: monkeypants
     - manual_qa: stinkyboots
     - qa_automation: sparkles-the-unicorn
   - nag_hours: 18
```
